version: "3.8"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hackathon
      MYSQL_DATABASE: db_hackathon
      MYSQL_USER: hackathon
      MYSQL_PASSWORD: hackathon
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
